language: go

go:
  - 1.8.x
  - tip

# to build ebiten
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
      - libc6-dev
      - libglu1-mesa-dev
      - libgl1-mesa-dev
      - libxcursor-dev
      - libxi-dev
      - libxinerama-dev
      - libxrandr-dev
      - libxxf86vm-dev
      - libasound2-dev
      - pkg-config

before_install:
  - go get -t -v ./...
  - go get github.com/mattn/goveralls

script:
  - $GOPATH/bin/goveralls -service=travis-ci